### ISSUE TITLE
Parsing Block Comments

### ISSUE THREAD

**Issue by juergenebert** [scireum/parsii#10]
I've noticed a small issue with block comments. The second example with the block comment directly starting after the + operand throws a ParseException. This would work in other libs like JEP.

	@Test
	public void blockComment() throws ParseException {
		assertEquals(29, Parser.parse("27+ /*xxx*/ 2").evaluate(), EPSILON);	// OK
		assertEquals(29, Parser.parse("27+/*xxx*/ 2").evaluate(), EPSILON);	// ERROR !
		assertEquals(29, Parser.parse("27/*xxx*/+2").evaluate(), EPSILON);		// OK
	}

**Comment by andyHa** [comment]
Fixed and released as parsii-1.6-SNAPSHOT (Availablke via Sonatype: https://oss.sonatype.org/content/groups/public/com/scireum/parsii/1.6-SNAPSHOT/)
Let me know if you need a release...
