### ISSUE TITLE
Add support for parentheses with positive sign

### ISSUE THREAD

**Issue by juergenebert** [scireum/parsii#11]
Could you please add support for parentheses with positive sign, like "+(2.2)". This currently leads to a parse error.

Background: I'm currently running a test with over 1.200.000 mathematical expressions from a real application which have been parsed by JEP and this seems to be the only remaining difference ..

Thank you!

  @Test
  public void signedParentheses() throws ParseException {
      assertEquals(0.2, Parser.parse("-(-0.2)").evaluate(), EPSILON);
      assertEquals(1.2, Parser.parse("1-(-0.2)").evaluate(), EPSILON);
      assertEquals(0.8, Parser.parse("1+(-0.2)").evaluate(), EPSILON);
      assertEquals(2.2, Parser.parse("+(2.2)").evaluate(), EPSILON); // ERROR !
  }

**Comment by andyHa** [comment]
Another 1.6-SNAPSHOT has been pushed...

Can you provide any information on the product you're working on - sounds quite interesting. (You can also send me an email (aha _AT_ scireum.de) if you don't want to share it here in public...)
