### ISSUE TITLE
Trailing decimal point and signed number after operand

### ISSUE THREAD

**Issue by juergenebert** [scireum/parsii#12]
Thank you very much for your support. I've found two more minor cases where Parsii throws an Exception, but they are considered legal in Java and JEP. Perhaps you might want to have a look at this.

Will write an email to you in the next days on what I'm currently doing ... :-)

    @Test
    public void trailingDecimalPoint() throws ParseException {
        assertEquals(2., Parser.parse("2.").evaluate(), EPSILON);  // ERROR
    }
  
    @Test
    public void signedValueAfterOperand() throws ParseException {
        assertEquals(-1.2, Parser.parse("1+-2.2").evaluate(), EPSILON);      // OK
        assertEquals(3.2, Parser.parse("1++2.2").evaluate(), EPSILON);       // ERROR
        assertEquals(6*-1.1, Parser.parse("6*-1.1").evaluate(), EPSILON);    // OK
        assertEquals(6*+1.1, Parser.parse("6*+1.1").evaluate(), EPSILON);    // ERROR
    }

**Comment by juergenebert** [comment]
The last code changes fixed only the last test case in error ("6*+1.1"), but the two other cases still throw an exception. Was that left unfixed on purpose?

**Comment by andyHa** [comment]
Nope, they should be fixed...

I pushed a new snapshot - maybe that'll fix the problem. This test passes:

assertEquals(-1.2, Parser.parse("1+-2.2").evaluate(),
BinaryOperation.EPSILON);
assertEquals(3.2, Parser.parse("1++2.2").evaluate(),
BinaryOperation.EPSILON);
assertEquals(6*-1.1, Parser.parse("6*-1.1").evaluate(),
BinaryOperation.EPSILON);
assertEquals(6*+1.1, Parser.parse("6*+1.1").evaluate(),
BinaryOperation.EPSILON);

freundliche Grüße
scireum GmbH

Andreas Haufler
Geschäftsführer

-------------------------------------------------------------------------------------------------------
scireum GmbH, Alfred-Klingele-Str. 6, 73630 Remshalden

Unser Service - gerne für Sie da:
Vertrieb: (07151) 90316 10
Support: (07151) 90316 20 - E-Mail: support@scireum.net

Tel.: (07151) 90316 21 - E-Mail:  aha@scireum.de
Fax: (07151) 90316 19 - Internet: http://www.scireum.de

Geschäftsführer: Michael Haufler, Andreas Haufler
Amtsgericht Stuttgart, HRB 732171

2015-02-12 16:07 GMT+01:00 Jürgen Ebert <notifications@github.com>:
