### ISSUE TITLE
Feature request: Add support for series variables

### ISSUE THREAD

**Issue by DanAvni** [scireum/parsii#13]
We need to do some calculations were the variables are a series of numbers. could add the following features?

1. Add support for a variable of type series. The variable obviously will hold a series of numbers (as a side note we could add support for direct series syntax as {1,2,3} without using a variable
2. Basic operators (+ - * /) on a series with a fixed value would produce as a result a series (e.g. 4*{1,2}={4,8}). 
3. Basic operators (+ - * /) on a series with another series would produce as a result a series where the series elements would have the operator applied to them (e.g. {2,3}*{1,2}={2,6}). Series have to be in the same length
4. add a new function SUM that takes as an input a series and calculates the sum of all items in the series

Would that be possible?

**Comment by andyHa** [comment]
Adding support for vectors adds quite a bit of complexity. So are you "just" talking about processing a single series using scalar operands or do you need to combine multiple series (which would result in matrix and vector operations). For the former, just compile the expression to be applied and iterate through your timeset manuall. Parsii is quite effective for that as it pre-optimizes the compiled expression.

Once you applied the expression simply use another loop or fance streams can Collectors to compute the sum. Let me know if that worked out for you.
