### ISSUE TITLE
Handle unknown variables

### ISSUE THREAD

**Issue by jourquin** [scireum/parsii#14]
I'm using JEP for years and I came recently over parsii. I find it a very lightweight and well written parser. The application in which I would like to implement parsii allows the final user to write its expressions in a simple text file. Obviously, mistakes can be typed in the expressions, such as making reference to non existent variables. For instance, if the user defines a=5 and b=7, but writes "a + c" as expression to parse, parsii will return 5 because it initializes c = 0, while it was never defined by the user.

JEP throws a special exception for undefined variables, which can be intercepted in order to warn the user that he made a mistake. If such a mechanism could be rather difficult to implement in parsii, a simple workaround is to modify the default value that is given to a Variable. So, in the Variable class, I replaced 
private double value = 0d; 
with
private double value = Double.NaN; 

Parsii will not throw an exception, but the Expression.evaluate(...) method will return a NaN if an unknown variable is references in the expression. Obviously, this is not perfect as it is not possible to give a precise information (which variable is unknown for instance), but, at least, the error is detected.

Is there any reason for which the default value is set to 0? If it is not the case, could this workaround be pushed in the source tree?

Regards,

Bart

**Comment by scireumskip** [comment]
Well thats a good idea. I added a method to Scope called
"Scope.createStrict". A Scope created by this factory method will throw a
ParseError if a yet unknown variable is referenced:

Scope s = Scope.createStrict();
try {
   s.create("a");
   s.create("b");
Parser.parse("a*b+c", s);
} catch (ParseException e) {
   assertEquals(1, e.getErrors().size());
}

parsii-2.1 should be visible in maven very soon....

freundliche Grüße
scireum GmbH

Andreas Haufler
Geschäftsführer

-------------------------------------------------------------------------------------------------------
scireum GmbH, Eisenbahnstr. 24, 73630 Remshalden

Unser Service - gerne für Sie da:
Vertrieb: +49 (0) 7151 90316 10
Support: +49 (0) 7151 90316 20 - E-Mail: support@scireum.net

Tel.: +49 (0) 7151 90316 21 - E-Mail:  aha@scireum.de
Fax: +49 (0) 7151 90316 19 - Internet: http://www.scireum.de

Geschäftsführer: Michael Haufler, Andreas Haufler
Amtsgericht Stuttgart, HRB 732171


2016-02-26 9:31 GMT+01:00 jourquin <notifications@github.com>:

**Comment by jourquin** [comment]
Thank you for your quick and efficient answer. This works great indeed.

Under some circumstances, it is also handy to have the possibility to remove a variable, without switching between different scopes. So I added the following method to Scope.java

/**
     * Removes a variable in this scope.
     * <p>
     * Tries to find a variable with the given name in this scope and removes it. If no variable with the given name is found,
     * the parent scope is not checked.
     *
     * @param name the of variable to remove
     * @return the previous value of the variable, or null if the variable was not found.
     */
    public Variable remove(String name) {
        if (context.containsKey(name)) {
            return context.remove(name);
        }
        return null;
    }

Maybe you could also push this in the tree ?

Bart

**Comment by scireumskip** [comment]
Added this method and cleaned ob the static methods (still there but
deprecated).... parsii-2.2 should be in maven soon...

freundliche Grüße
scireum GmbH

Andreas Haufler
Geschäftsführer

-------------------------------------------------------------------------------------------------------
scireum GmbH, Eisenbahnstr. 24, 73630 Remshalden

Unser Service - gerne für Sie da:
Vertrieb: +49 (0) 7151 90316 10
Support: +49 (0) 7151 90316 20 - E-Mail: support@scireum.net

Tel.: +49 (0) 7151 90316 21 - E-Mail:  aha@scireum.de
Fax: +49 (0) 7151 90316 19 - Internet: http://www.scireum.de

Geschäftsführer: Michael Haufler, Andreas Haufler
Amtsgericht Stuttgart, HRB 732171


2016-02-26 13:07 GMT+01:00 Bart Jourquin <notifications@github.com>:

**Comment by jourquin** [comment]
Great! Thank you very much.
