### ISSUE TITLE
Cross compile option not working?

### ISSUE THREAD

**Issue by juergenebert** [scireum/parsii#15]
Although the POM states <maven.compiler.target>1.6</maven.compiler.target>, the resulting JAR from a compile with JDK 8 is not runnable under Java 7 ("unsupported major.minor version 52.0"). The same problem occurs with the parsii-2.2.jar downloaded from Maven central. Am I doing something wrong or is the cross compile option not working? 
Thank you, Jürgen

**Comment by andyHa** [comment]
I changed the pom - 2.3 should (hopefully now be "down" compiled to 1.6) - let me know if that works

**Comment by juergenebert** [comment]
Yes, this works! Thank you again for your quick support!
