### ISSUE TITLE
Is there a way to get a max value?

### ISSUE THREAD

**Issue by incompl** [scireum/parsii#25]
I tried to do max(variable) but it didn't work. Is there a way to do it?

**Comment by Scoppio** [comment]
is this max from multiple values?
The max should be max(var1, var2) and then it returns the bigger one.
If you need the max from an array, Id go with something like a new expression, something like...
```

    /**
     * Max from array
     * max(3,3,5,1) = 5
     */
    private static final parsii.eval.Function MAX_VEC = new parsii.eval.Function() {

        @Override
        public double eval(List<Expression> args) {

            double max = Double.NaN;

            if (args.isEmpty()) {
                throw new NullpointerException();
            }

            List<Double> values = new ArrayList<>();

            for(Expression arg: args) {
                values.add(arg.evaluate());
            }

            for (Double aValue : values) {
                if (aValue > max) {
                    max = aValue;
                }
            }
            return max;
        }

        @Override
        public int getNumberOfArguments() {
            return -1;
        }

        @Override
        public boolean isNaturalFunction() {
            return true;
        }
    };

```

Now, if you need to deal with an array, It would require some experimentation.

**Comment by incompl** [comment]
max(var1, var2) is just what I needed! Thank you! Is there a reference doc or standard somewhere that has these listed?

**Comment by Scoppio** [comment]
To be honest with you, the only "document" that there is for this library is the single test file it has. I had to learn how those functions work, etc, by reading the library itself.
The file "Functions" has a good documentation, should be enough for most cases.

**Comment by incompl** [comment]
Nice, this is very useful. [Here is the link for anyone who stumbles upon this issue](https://github.com/scireum/parsii/blob/bc9719b94f58767579e9cc783a7bbfa92fb86543/src/main/java/parsii/eval/Functions.java). Would be cool if the JavaDoc could be built into a GitHub pages site or something. Thanks!
