### ISSUE TITLE
Scientific notation

### ISSUE THREAD

**Issue by jourquin** [scireum/parsii#28]
Hi,

It seems that Parsii doesn't like scientific notations... Did I miss something ?

```
String value = "-5.408380743914645e-10";

// Simple Java is working
double d = Double.valueOf(value);

// The parser throws an error : " Unexpected token: 'e'. Expected a valid quantifier."
    try {
      Parser.parse(value).evaluate();
    } catch (ParseException e) {
      e.printStackTrace();
    }

**Comment by shayelk** [comment]
Make sure you're not using a (very) old version: commit 89810acb3e9ad888ec1ed840c5ab98cfdb670c93 added support of scientific notation, and was merged on May 28, 2019

**Comment by jourquin** [comment]
Thank you for your quick answer. I'm using parsii-5.0.1, which is the latest version I think...

**Comment by jourquin** [comment]
Sorry, It seems that I had 2 versions of parsii on my classpath.... Its working :-)
