### ISSUE TITLE
Is this thread safe?

### ISSUE THREAD

**Issue by f0re1gnKey** [scireum/parsii#29]
Is this thread safe, or is there any way to use it thread safely without synchronized?

**Comment by andyHa** [comment]
A parser isn't. But once a parsed expression (Expression) is available, it is never modified anymore and can be shared across threads safely. Also, "Scope" internally uses ConcurrentHashMaps and thus can be shared as well. However, a Variable internally uses a "double value" which isn't marked as atomic. This might see some false sharing - depending on the load and CPU cache hierarchy. However, this could be changed very easily.
