### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by juergenebert** [scireum/parsii#8]
Very good library! But the following test case produces a parse error because of the '+' sign in front of the numeric literal. Would have expected this to work. Any chance to see this working in the next release? Thank you!

       @Test
	public void signed() throws ParseException {
		assertEquals(2.02, Parser.parse("+2.02").evaluate(), 0.0000001);
	}

**Comment by andyHa** [comment]
parsii-1.5 hast just been pushed to the central repository (should be visible within a few hours)

**Comment by juergenebert** [comment]
Wow, that fix was really fast! Thank you very much!
