### ISSUE TITLE
Floating-point literals starting with decimal point

### ISSUE THREAD

**Issue by juergenebert** [scireum/parsii#9]
Per Java language specification, floating point literats may start with the decimal point, eg. ".2". This leads to a parser error in Parsii. Would be great to see this in Parsii, too ..

  @Test
  public void startingWithDecimalPoint() throws ParseException {
      // Throws a ParseException
      assertEquals(.2, Parser.parse(".2").evaluate(), EPSILON);
  }

**Comment by andyHa** [comment]
now also supports +.2 and .2+-.2 ;-)
